server:
  grpc_port: 50051

database:
  host: localhost
  port: 5432
  user: auth_user
  password: auth_pass
  dbname: auth_db
  sslmode: disable

jwt:
  secret: "supersecretjwtkey1234567890"  
  ttl_minutes: 60                       