server:
  grpc_port: 50051

database:
  host: auth-db
  port: 5432
  user: auth_user
  password: auth_pass
  dbname: auth_db
  sslmode: disable

jwt:
  secret: "supersecretjwtkey1234567890"  
  ttl: 60m                   