server:
  host: 0.0.0.0
  port: 50052

database:
  host: goods-db
  port: 5432
  user: goods_user
  password: goods_pass
  dbname: goods_db
  sslmode: disable

auth_service:
  address: auth-service:50051

redis:
  addr: redis:6379
  password: ""
  db: 0
